name: 'pylint pytest'
description: 'run pylint and pytest with coverage if possible'
inputs:
  module_name:
    description: 'name of the python module in the repository'
    required: true
    default: 'NOT_SET'

runs:
  using: "composite"
  steps:
    - shell: bash
      run: echo "${{ inputs.module_name }}"
    - run: pylint --rcfile=.pylintrc ${MODULE_NAME}
      shell: bash
    - run: pytest --cov=${MODULE_NAME} -v
      shell: bash
