name: 'pylint pytest'
description: 'run pylint and pytest with coverage if possible'
inputs:
  module_name:
    description: 'name of the python module in the repository'
    required: true
    default: 'NOT_SET'

runs:
  using: "composite"
  steps:
    - shell: bash
      run: echo "${{ inputs.module_name }}"
    - shell: bash
      run: echo "${{ env.GITHUB_WORKSPACE }}/tests"
    - run: python -m pip install --upgrade pip
      shell: bash
    - run: pip install pytest pytest-cov pylint
      shell: bash
    - run: if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      shell: bash
    - run: if [ -f requirements_test.txt ]; then pip install -r requirements_test.txt; fi
      shell: bash
    - run: pylint --rcfile=.pylintrc ${{ inputs.module_name }} || exit 0
      shell: bash
    - run: if [ -d "${{ env.GITHUB_WORKSPACE }}/tests"  ]; then pytest --cov=${{ inputs.module_name }} -v; else echo "tests not found" && exit 0; fi
      shell: bash
