name: 'pylint pytest'
description: 'run pylint and pytest with coverage if possible'
inputs:
  module_name:
    description: 'name of the python module in the repository'
    required: true
    default: 'NOT_SET'

runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/run_action.sh
      shell: bash